sudo: required
services:
  - docker

before_install:
  - docker build -t happynasit001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true happynasit001/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "place where you created this beanstalk"
  app: "the name you put there in the beanstalk"
  env: "name of the configuration, also in the beanstalk"
  bucket_name: ""
  bucket_path: "same as the app"
  on:
    branch: master